development:
  adapter: mysql
  encoding: utf8
  reconnect: true
  database: nkbook_development
  pool: 10
  username: root
  password:

test:
  adapter: mysql
  encoding: utf8
  reconnect: true
  database: nkbook_test
  pool: 10
  username: root
  password:

production:
  adapter: mysql
  encoding: utf8
  reconnect: true
  database: nkbook_development
  pool: 10
  username: root
  password:
